package com.aux_arena.models.session.round;

import com.aux_arena.models.session.PlayerState;
import com.aux_arena.models.session.UserSession;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Prompt {

    private String prompt;

    // determines if the prompt was generated by
    private boolean wasGenerated;

    // if this is null that means the system generated it
    private String authorId;

}